### ISSUE TITLE
Listing on Terraform Registry

### ISSUE THREAD

**Issue by ksatirli** [davislx/terraform-provider-bitly#1]
Hello @davislx,

Thank you for your work on this provider! I'm curious: would you be amenable to publishing this provider on the [Terraform Registry](https://registry.terraform.io)?

**Comment by davislx** [comment]
@ksatirli Sorry about the delay, I am open to that. However, I don't think this provider is features complete yet. I created this for experiment purpose.

**Comment by ksatirli** [comment]
Hey @davislx! No worries at all about a delay.

My question stems from making the provider more accessible and easier to install, which might get you access to more user feedback (if that's something you're looking for).

**Comment by sokraflex** [comment]
Hi @ksatirli

Since I want to experiment with the bitly API as well, I took the liberty of [creating a fork](https://github.com/sokraflex/terraform-provider-bitly) and [publishing it on the registry](https://registry.terraform.io/providers/sokraflex/bitly/latest).
For anyone who wants to give the provider a quick test, it's there!
